baseURL = "/"
title = "BeliefCraft Innovation (术源创新)"
theme = "bcitheme"
hasCJKLanguage = true
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

[languages]
  [languages.zh]
    languageCode = "zh-cn"
    languageName = "中文"
    weight = 1
  [languages.en]
    languageCode = "en-us"
    languageName = "EN"
    weight = 2
